name: A Gift of Love
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75507
title: A Gift of Love
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#563428'
    - '#a61a23'
    - '#c85c1b'
    - '#f7b97e'
    - '#ccdadb'
  brandStrength: 0.9375
  lightness: 0.0625
  saturation: 0.8918368362355977
  rhythmicContrast: 0.75
purpose: []
