name: A Gift of Love
favicon: null
layout_spectrum: 0.5411
typography_spectrum: 0.75507
title: A Gift of Love
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#563428'
    - '#a61a23'
    - '#c85c1b'
    - '#f7b97e'
    - '#ccdadb'
  brandStrength: 0
  lightness: 0.3125
  saturation: 1
  rhythmicContrast: 1
purpose: []
